### PR TITLE
updates profile now

### PR DESCRIPTION
**Pull request by Uproxide**
makes it where it sets the name in your profile sets to the custom name

### CODE REVIEW

**Comment by coopeeo** [comment]
omfg thanks so much! i was gonna do this. also im just starting in C++ and learning it by doing this. thanks so much!!!

**Review by coopeeo — APPROVED** [review]
good

**Comment by coopeeo** [comment]
wait shit why did i squash not just do it normally mr adhd mind (me) anyway it works! Thanks so much

**Comment by Uproxide** [comment]
np :)

**Comment by Uproxide** [comment]
im also starting in c++, took awhile to learn fields and i finally did it

**Comment by coopeeo** [comment]
same!

**Pull request merged**
